Repository ixi-U/ixi-U-be, pull requests merged in 2025-06, with the labels that each got.

#3 [chore]:[SCRUM-20] CI 파이프라인 구성
  .github/workflows/ci.yml
  build.gradle
  src/test/java/com/ixi_U/IxiUApplicationTests.java
  src/test/resources/application-test.yml
Labels: chore

#6 [chore]:[SCRUM-25] CD 파이프라인 구성
  .github/workflows/cd.yml
  appspec.yml
  scripts/install.sh
  scripts/start.sh
Labels: chore

#10 [fix]:[SCRUM-31] CD 과정에서 빌드 방식 변경
  .github/workflows/cd.yml
Labels: fix

#11 [fix]:[SCRUM-32] 배포 과정 테스트 코드 실패건 수정
  src/test/java/com/ixi_U/chatbot/controller/ChatBotControllerTest.java
  src/test/java/com/ixi_U/chatbot/service/ChatBotServiceTest.java
Labels: fix

#9 [feat]:[SCRUM 16] 요금제 리뷰 생성, 조회
  build.gradle
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/ixi_U/common/exception/GlobalExceptionHandler.java
  src/main/java/com/ixi_U/plan/exception/PlanException.java
  src/main/java/com/ixi_U/plan/repository/PlanRepository.java
  src/main/java/com/ixi_U/user/controller/ReviewController.java
  src/main/java/com/ixi_U/user/dto/request/CreateReviewRequest.java
  src/main/java/com/ixi_U/user/dto/response/ShowReviewListResponse.java
  src/main/java/com/ixi_U/user/dto/response/ShowReviewResponse.java
  src/main/java/com/ixi_U/user/entity/Reviewed.java
  src/main/java/com/ixi_U/user/entity/Subscribed.java
  src/main/java/com/ixi_U/user/exception/ReviewedException.java
  src/main/java/com/ixi_U/user/exception/SubscribedException.java
  src/main/java/com/ixi_U/user/exception/UserException.java
  src/main/java/com/ixi_U/user/repository/ReviewedRepository.java
  src/main/java/com/ixi_U/user/repository/SubscribedRepository.java
  src/main/java/com/ixi_U/user/repository/UserRepository.java
  src/main/java/com/ixi_U/user/service/ReviewService.java
  src/test/java/com/ixi_U/user/controller/ReviewControllerTest.java
  src/test/java/com/ixi_U/user/repository/ReviewedRepositoryTest.java
  src/test/java/com/ixi_U/user/repository/SubscribedRepositoryTest.java
  src/test/java/com/ixi_U/user/service/ReviewServiceTest.java
  src/test/resources/application-test.yml
Labels: feat

#8 [feat]:[SCRUM 14] 요금제 목록 조회
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/ixi_U/plan/controller/PlanController.java
  src/main/java/com/ixi_U/plan/dto/PlanSummaryDto.java
  src/main/java/com/ixi_U/plan/dto/request/GetPlansRequest.java
  src/main/java/com/ixi_U/plan/dto/response/SortedPlanResponse.java
  src/main/java/com/ixi_U/plan/entity/Comparison.java
  src/main/java/com/ixi_U/plan/entity/Plan.java
  src/main/java/com/ixi_U/plan/entity/PlanSortOption.java
  src/main/java/com/ixi_U/plan/entity/PlanType.java
  src/main/java/com/ixi_U/plan/entity/SortOrder.java
  src/main/java/com/ixi_U/plan/exception/PlanException.java
  src/main/java/com/ixi_U/plan/repository/PlanCustomRepository.java
  src/main/java/com/ixi_U/plan/repository/PlanRepository.java
  src/main/java/com/ixi_U/plan/repository/PlanRepositoryImpl.java
  src/main/java/com/ixi_U/plan/service/PlanService.java
  src/test/java/com/ixi_U/plan/controller/PlanControllerTest.java
  src/test/java/com/ixi_U/plan/repository/PlanRepositoryTest.java
  src/test/java/com/ixi_U/plan/service/PlanServiceTest.java
  src/test/java/com/ixi_U/user/repository/ReviewedRepositoryTest.java
  src/test/java/com/ixi_U/user/repository/SubscribedRepositoryTest.java
  src/test/java/com/ixi_U/user/service/ReviewServiceTest.java
Labels: feat

#15 [fix]:[SCRUM-37] 요금제 목록 조회 테스트 수정
  src/test/java/com/ixi_U/plan/controller/PlanControllerTest.java
  src/test/java/com/ixi_U/plan/repository/PlanRepositoryTest.java
  src/test/java/com/ixi_U/plan/service/PlanServiceTest.java
Labels: fix

#7 [feat]:[SCRUM-21] 유저의 사용 중인 요금제 등록
  .gitignore
  build.gradle
  src/main/java/com/ixi_U/IxiUApplication.java
  src/main/java/com/ixi_U/benefit/entity/BundledBenefit.java
  src/main/java/com/ixi_U/benefit/entity/SingleBenefit.java
  src/main/java/com/ixi_U/common/config/Neo4jConfig.java
  src/main/java/com/ixi_U/common/exception/enums/PlanException.java
  src/main/java/com/ixi_U/common/exception/enums/UserException.java
  src/main/java/com/ixi_U/plan/entity/Plan.java
  src/main/java/com/ixi_U/plan/repository/PlanRepository.java
  src/main/java/com/ixi_U/user/controller/SubscribedController.java
  src/main/java/com/ixi_U/user/dto/CreateSubscribedRequest.java
  src/main/java/com/ixi_U/user/entity/Reviewed.java
  src/main/java/com/ixi_U/user/entity/Subscribed.java
  src/main/java/com/ixi_U/user/entity/User.java
  src/main/java/com/ixi_U/user/repository/UserRepository.java
  src/main/java/com/ixi_U/user/service/SubscribedService.java
  src/main/java/com/ixi_U/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/ixi_U/IxiUApplicationTests.java
  src/test/java/com/ixi_U/common/AbstractNeo4jContainer.java
  src/test/java/com/ixi_U/common/config/FakeNeo4jAuditingConfig.java
  src/test/java/com/ixi_U/user/controller/SubscribedControllerTest.java
  src/test/java/com/ixi_U/user/repository/ReviewedRepositoryTest.java
  src/test/java/com/ixi_U/user/repository/SubscribedRepositoryTest.java
  src/test/java/com/ixi_U/user/repository/UserAndPlanRepositoryTest.java
  src/test/java/com/ixi_U/user/service/SubscribedServiceTest.java
Labels: feat

#16 [feat]:[SCRUM-19] 소셜 로그인 및 jwt 토큰 인증/인가 기능 구현
  build.gradle
  src/main/java/com/ixi_U/IxiUApplication.java
  src/main/java/com/ixi_U/auth/dto/KakaoTokenResponse.java
  src/main/java/com/ixi_U/auth/dto/KakaoUserResponse.java
  src/main/java/com/ixi_U/auth/exception/KakaoAuthException.java
  src/main/java/com/ixi_U/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/ixi_U/auth/service/CustomOAuth2UserService.java
  src/main/java/com/ixi_U/common/config/RestTemplateConfig.java
  src/main/java/com/ixi_U/common/config/SecurityConfig.java
  src/main/java/com/ixi_U/common/exception/runtime/ErrorCode.java
  src/main/java/com/ixi_U/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ixi_U/jwt/JwtTokenProvider.java
  src/main/java/com/ixi_U/jwt/exception/JwtErrorCode.java
  src/main/java/com/ixi_U/user/controller/UserController.java
  src/main/java/com/ixi_U/user/dto/response/PlanResponse.java
  src/main/java/com/ixi_U/user/dto/response/SubscribedResponse.java
  src/main/java/com/ixi_U/user/entity/User.java
  src/main/java/com/ixi_U/user/repository/UserRepository.java
  src/main/java/com/ixi_U/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/ixi_U/chatbot/controller/ChatBotControllerTest.java
  src/test/java/com/ixi_U/user/repository/ReviewedRepositoryTest.java
  src/test/java/com/ixi_U/user/repository/SubscribedRepositoryTest.java
  src/test/java/com/ixi_U/user/repository/UserAndPlanRepositoryTest.java
  src/test/java/com/ixi_U/user/repository/UserRepositoryTest.java
  src/test/java/com/ixi_U/user/service/ReviewServiceTest.java
  src/test/java/com/ixi_U/user/service/SubscribedServiceTest.java
  src/test/resources/application-test.yml
Labels: feat

#13 [feat]:[SCRUM-29] 챗봇 요금제 요약 응답 기능 추가
  build.gradle
  src/main/java/com/ixi_U/chatbot/config/ChatBotConfig.java
  src/main/java/com/ixi_U/chatbot/controller/ChatBotController.java
  src/main/java/com/ixi_U/chatbot/dto/BundledBenefitRequest.java
  src/main/java/com/ixi_U/chatbot/dto/PlanDescriptionRequest.java
  src/main/java/com/ixi_U/chatbot/dto/SingleBenefitRequest.java
  src/main/java/com/ixi_U/chatbot/exception/ChatBotException.java
  src/main/java/com/ixi_U/chatbot/service/ChatBotService.java
  src/main/java/com/ixi_U/common/exception/GlobalExceptionHandler.java
  src/main/java/lombok.config
  src/main/resources/prompts/description.txt
  src/test/java/com/ixi_U/chatbot/controller/ChatBotControllerTest.java
  src/test/java/com/ixi_U/chatbot/service/ChatBotServiceTest.java
  src/test/java/com/ixi_U/chatbot/testutil/TestDataFactory.java
Labels: feat

#20 [fix]:[SCRUM-50] 소셜 로그인 로직 수정
  src/main/java/com/ixi_U/auth/dto/CustomOAuth2User.java
  src/main/java/com/ixi_U/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/ixi_U/auth/service/CustomOAuth2UserService.java
  src/main/java/com/ixi_U/benefit/controller/BenefitController.java
  src/main/java/com/ixi_U/benefit/dto/request/SaveBundledBenefitRequest.java
  src/main/java/com/ixi_U/benefit/dto/request/SaveSingleBenefitRequest.java
  src/main/java/com/ixi_U/benefit/dto/response/FindBundledBenefitResponse.java
  src/main/java/com/ixi_U/benefit/dto/response/FindSingleBenefitResponse.java
  src/main/java/com/ixi_U/benefit/entity/BundledBenefit.java
  src/main/java/com/ixi_U/benefit/entity/SingleBenefit.java
  src/main/java/com/ixi_U/benefit/repository/BundledBenefitRepository.java
  src/main/java/com/ixi_U/benefit/repository/SingleBenefitRepository.java
  src/main/java/com/ixi_U/benefit/service/BenefitService.java
  src/main/java/com/ixi_U/common/config/SecurityConfig.java
  src/main/java/com/ixi_U/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ixi_U/jwt/JwtTokenProvider.java
  src/main/java/com/ixi_U/user/entity/User.java
  src/main/java/com/ixi_U/user/entity/UserRole.java
  src/main/java/com/ixi_U/user/repository/UserRepository.java
  src/main/resources/application.yml
  src/test/java/com/ixi_U/chatbot/controller/ChatBotControllerTest.java
  src/test/java/com/ixi_U/user/repository/ReviewedRepositoryTest.java
  src/test/java/com/ixi_U/user/repository/SubscribedRepositoryTest.java
  src/test/java/com/ixi_U/user/repository/UserAndPlanRepositoryTest.java
  src/test/java/com/ixi_U/user/repository/UserRepositoryTest.java
  src/test/java/com/ixi_U/user/service/ReviewServiceTest.java
  src/test/java/com/ixi_U/user/service/SubscribedServiceTest.java
Labels: fix

#17 [fix]:[SCRUM-39] 배포 과정에서 start.sh에서 발생하는 오류 수정
  build.gradle
  scripts/start.sh
  src/main/java/com/ixi_U/common/config/SecurityConfig.java
  src/main/java/com/ixi_U/jwt/JwtAuthenticationFilter.java
  src/main/resources/application.yml
Labels: fix

#21 [feat]:[SCRUM 41] 레벤슈타인 기반 금칙어 구현
  src/main/java/com/ixi_U/common/filter/ForbiddenWordFilter.java
  src/main/java/com/ixi_U/common/filter/ForbiddenWordLoader.java
  src/main/java/com/ixi_U/common/filter/WordPreprocessingPolicy.java
  src/main/resources/forbidden-words.txt
Labels: feat

#22 [feat]:[SCRUM-15] 요금제 상세 정보 조회 기능 구현
  .github/workflows/cd.yml
  .github/workflows/create-api-doc.yml
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/ixi_U/benefit/entity/BenefitType.java
  src/main/java/com/ixi_U/plan/controller/PlanController.java
  src/main/java/com/ixi_U/plan/dto/response/BundledBenefitResponse.java
  src/main/java/com/ixi_U/plan/dto/response/PlanDetailResponse.java
  src/main/java/com/ixi_U/plan/dto/response/SingleBenefitResponse.java
  src/main/java/com/ixi_U/plan/service/PlanService.java
  src/test/java/com/ixi_U/plan/controller/PlanControllerTest.java
Labels: feat

#26 [feat]:[SCRUM-34] 요금제 등록 기능
  build.gradle
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/ixi_U/benefit/entity/BundledBenefit.java
  src/main/java/com/ixi_U/chatbot/dto/BundledBenefitDTO.java
  src/main/java/com/ixi_U/chatbot/dto/BundledBenefitRequest.java
  src/main/java/com/ixi_U/chatbot/dto/GeneratePlanDescriptionRequest.java
  src/main/java/com/ixi_U/chatbot/dto/PlanDescriptionRequest.java
  src/main/java/com/ixi_U/chatbot/dto/SingleBenefitDTO.java
  src/main/java/com/ixi_U/chatbot/dto/SingleBenefitRequest.java
  src/main/java/com/ixi_U/chatbot/service/ChatBotService.java
  src/main/java/com/ixi_U/chatbot/service/VectorService.java
  src/main/java/com/ixi_U/plan/controller/PlanController.java
  src/main/java/com/ixi_U/plan/dto/request/SavePlanRequest.java
  src/main/java/com/ixi_U/plan/dto/response/PlanEmbeddedResponse.java
  src/main/java/com/ixi_U/plan/entity/Plan.java
  src/main/java/com/ixi_U/plan/entity/PlanState.java
  src/main/java/com/ixi_U/plan/exception/PlanException.java
  src/main/java/com/ixi_U/plan/repository/PlanRepository.java
  src/main/java/com/ixi_U/plan/service/PlanService.java
  src/main/java/com/ixi_U/user/service/UserService.java
  src/main/resources/prompts/description.txt
  src/test/java/com/ixi_U/chatbot/constants/TestConstants.java
  src/test/java/com/ixi_U/chatbot/controller/ChatBotControllerTest.java
  src/test/java/com/ixi_U/chatbot/service/ChatBotServiceTest.java
  src/test/java/com/ixi_U/chatbot/testutil/TestDataFactory.java
  src/test/java/com/ixi_U/plan/controller/PlanControllerTest.java
  src/test/java/com/ixi_U/util/constants/TestConstants.java
Labels: feat

#25 [feat]:[SCRUM 55] 리뷰 수정 및 삭제 기능
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/ixi_U/user/controller/ReviewController.java
  src/main/java/com/ixi_U/user/dto/request/UpdateReviewRequest.java
  src/main/java/com/ixi_U/user/dto/response/ShowReviewResponse.java
  src/main/java/com/ixi_U/user/dto/response/ShowReviewSummaryResponse.java
  src/main/java/com/ixi_U/user/exception/ReviewedException.java
  src/main/java/com/ixi_U/user/repository/ReviewedRepository.java
  src/main/java/com/ixi_U/user/repository/UserRepository.java
  src/main/java/com/ixi_U/user/service/ReviewService.java
  src/test/java/com/ixi_U/user/controller/ReviewControllerTest.java
  src/test/java/com/ixi_U/user/service/ReviewServiceTest.java
Labels: feat

#27 [feat]:[SCRUM-48] 회원 탈퇴 기능
  src/main/java/com/ixi_U/user/controller/UserController.java
  src/main/java/com/ixi_U/user/repository/SubscribedRepository.java
  src/main/java/com/ixi_U/user/service/UserService.java
  src/test/java/com/ixi_U/user/controller/SubscribedControllerTest.java
  src/test/java/com/ixi_U/user/service/UserServiceTest.java
Labels: feat

#31 [fix]:[SCRUM-59] 요금제 목록 조회 기능 수정
  src/main/java/com/ixi_U/plan/dto/PlanSummaryDto.java
  src/main/java/com/ixi_U/plan/repository/PlanRepositoryImpl.java
  src/test/java/com/ixi_U/plan/controller/PlanControllerTest.java
  src/test/java/com/ixi_U/plan/service/PlanServiceTest.java
Labels: fix

#29 [feat]:[SCRUM-53] LLM 기반 금칙어 필터 기능(임시)
  src/main/java/com/ixi_U/chatbot/config/ChatBotConfig.java
  src/main/java/com/ixi_U/chatbot/service/ChatBotForBiddenWordDecisionService.java
Labels: feat

#33 [feat]:[SCRUM-63] CORS 설정 추가
  src/main/java/com/ixi_U/common/config/SecurityConfig.java
Labels: feat

#30 [chore]:[SCRUM-60] 회원 시스템 Spring Rest Docs 추가
  src/docs/asciidoc/api-doc.adoc
Labels: chore

#36 [fix]:[SCRUM-68] 직전 요금제가 중복 구독이 되는 에러 수정
  src/main/java/com/ixi_U/user/service/SubscribedService.java
Labels: fix

#41 [feat]:[SCRUM-27] 벡터 기반 유사도 검색 기능
  build.gradle
  src/main/java/com/ixi_U/IxiUApplication.java
  src/main/java/com/ixi_U/benefit/entity/BenefitType.java
  src/main/java/com/ixi_U/chatbot/config/ChatBotConfig.java
  src/main/java/com/ixi_U/chatbot/config/VectorStoreConfig.java
  src/main/java/com/ixi_U/chatbot/controller/ChatBotController.java
  src/main/java/com/ixi_U/chatbot/dto/GeneratePlanDescriptionRequest.java
  src/main/java/com/ixi_U/chatbot/dto/RecommendPlanRequest.java
  src/main/java/com/ixi_U/chatbot/exception/ChatBotException.java
  src/main/java/com/ixi_U/chatbot/service/ChatBotService.java
  src/main/java/com/ixi_U/chatbot/service/VectorStoreService.java
  src/main/java/com/ixi_U/chatbot/tool/RecommendTool.java
  src/main/java/com/ixi_U/plan/controller/PlanController.java
  src/main/java/com/ixi_U/plan/entity/Plan.java
  src/main/java/com/ixi_U/plan/service/PlanService.java
  src/main/resources/application.yml
  src/main/resources/prompts/embedding-prompt.txt
  src/main/resources/prompts/filter-expression-prompt.txt
  src/main/resources/prompts/recommending-prompt.txt
  src/test/java/com/ixi_U/TestWebFluxSecurityConfig.java
  src/test/java/com/ixi_U/chatbot/controller/ChatBotControllerTest.java
  src/test/java/com/ixi_U/chatbot/service/ChatBotServiceTest.java
  src/test/java/com/ixi_U/plan/controller/PlanControllerTest.java
  src/test/java/com/ixi_U/util/constants/TestConstants.java
Labels: feat

#42 [feat]:[SCRUM-66] 금칙어 시스템 최종 구현
  src/main/java/com/ixi_U/chatbot/config/ChatBotConfig.java
  src/main/java/com/ixi_U/chatbot/config/VectorStoreConfig.java
  src/main/java/com/ixi_U/chatbot/service/ChatBotService.java
  src/main/java/com/ixi_U/common/config/Neo4jConfig.java
  src/main/java/com/ixi_U/common/forbiddenWord/ForbiddenWordSimilarityService.java
  src/main/java/com/ixi_U/forbiddenWord/ChatbotFilter.java
  src/main/java/com/ixi_U/forbiddenWord/ForbiddenWordController.java
  src/main/java/com/ixi_U/forbiddenWord/ForbiddenWordLoader.java
  src/main/java/com/ixi_U/forbiddenWord/ReviewFilter.java
  src/main/java/com/ixi_U/forbiddenWord/WordPreprocessingPolicy.java
  src/main/java/com/ixi_U/forbiddenWord/filters/AhoCorasickFilter.java
  src/main/java/com/ixi_U/forbiddenWord/filters/EmbeddingSimilarityFilter.java
  src/main/java/com/ixi_U/forbiddenWord/filters/ForbiddenWordFilter.java
  src/main/java/com/ixi_U/forbiddenWord/filters/LevenshteinThresholdFilter.java
  src/main/java/com/ixi_U/forbiddenWord/filters/LlmFilter.java
  src/main/resources/forbidden-words.txt
Labels: feat

#34 [feat]:[SCRUM-46] 신규 유저 온보딩 화면 정보 DB 저장 구현
  .gitignore
  src/main/java/com/ixi_U/common/config/SecurityConfig.java
  src/main/java/com/ixi_U/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ixi_U/plan/controller/PlanController.java
  src/main/java/com/ixi_U/plan/dto/PlanNameDto.java
  src/main/java/com/ixi_U/plan/dto/response/PlanIdAndNameResponse.java
  src/main/java/com/ixi_U/plan/repository/PlanRepository.java
  src/main/java/com/ixi_U/plan/service/PlanService.java
  src/main/java/com/ixi_U/user/controller/UserController.java
  src/main/java/com/ixi_U/user/dto/request/OnboardingRequest.java
  src/main/java/com/ixi_U/user/entity/User.java
  src/main/java/com/ixi_U/user/service/UserService.java
  src/main/resources/static/docs/api-doc.html
  src/test/java/com/ixi_U/plan/controller/PlanControllerTest.java
  src/test/java/com/ixi_U/plan/service/PlanServiceTest.java
  src/test/java/com/ixi_U/user/controller/OnboardingControllerTest.java
Labels: feat, fix

#43 [feat]:[SCRUM-34] 어드민 유저 요금제 등록 및 상태 수정(able/disable) 기능 구현
  src/main/java/com/ixi_U/common/config/SecurityConfig.java
  src/main/java/com/ixi_U/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ixi_U/jwt/JwtTokenProvider.java
  src/main/java/com/ixi_U/plan/controller/PlanController.java
  src/main/java/com/ixi_U/plan/dto/response/PlanAdminResponse.java
  src/main/java/com/ixi_U/plan/entity/Plan.java
  src/main/java/com/ixi_U/plan/repository/PlanRepository.java
  src/main/java/com/ixi_U/plan/service/PlanService.java
  src/test/java/com/ixi_U/plan/controller/PlanControllerTest.java
Labels: feat, fix

#44 [fix]:[SCRUM-63] 잘못된 CORS 설정 수정
  src/main/java/com/ixi_U/common/config/SecurityConfig.java
Labels: fix

#45 [fix]:[SCRUM-63] 잘못된 테스트 설정 수정
  src/test/java/com/ixi_U/user/controller/OnboardingControllerTest.java
Labels: fix

#46 [feat]:[SCRUM-85] 챗봇 API 명세 추가
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/ixi_U/chatbot/config/ChatBotConfig.java
  src/main/java/com/ixi_U/chatbot/dto/BundledBenefitDTO.java
  src/main/java/com/ixi_U/chatbot/dto/GeneratePlanDescriptionRequest.java
  src/main/java/com/ixi_U/chatbot/service/ChatBotService.java
  src/main/java/com/ixi_U/chatbot/service/VectorStoreService.java
  src/main/java/com/ixi_U/chatbot/tool/RecommendTool.java
  src/main/java/com/ixi_U/chatbot/tool/ToolContextKey.java
  src/main/java/com/ixi_U/plan/entity/Plan.java
  src/main/java/com/ixi_U/plan/service/PlanService.java
  src/main/resources/prompts/filter-expression-prompt.txt
  src/test/java/com/ixi_U/chatbot/controller/ChatBotControllerTest.java
  src/test/java/com/ixi_U/chatbot/testutil/TestDataFactory.java
Labels: feat

#48 [feat]:[SCRUM-95] 챗봇 API 시큐리티 적용
  src/main/java/com/ixi_U/chatbot/controller/ChatBotController.java
  src/test/java/com/ixi_U/chatbot/controller/ChatBotControllerTest.java
Labels: feat

#47 [feat]:[SCRUM-94] 금칙어 시스템 성능 개선
  build.gradle
  src/main/java/com/ixi_U/forbiddenWord/ChatbotFilter.java
  src/main/java/com/ixi_U/forbiddenWord/ForbiddenWordController.java
  src/main/java/com/ixi_U/forbiddenWord/KoreanAnalyzeService.java
  src/main/java/com/ixi_U/forbiddenWord/filters/EmbeddingSimilarityFilter.java
  src/main/resources/forbidden-words.txt
Labels: feat

#57 [feat]:[SCRUM-100] 챗봇 응답 튜닝
  src/main/java/com/ixi_U/chatbot/config/ChatBotConfig.java
  src/main/java/com/ixi_U/chatbot/exception/ChatBotException.java
  src/main/java/com/ixi_U/chatbot/service/ChatBotService.java
  src/main/java/com/ixi_U/chatbot/service/VectorStoreService.java
  src/main/java/com/ixi_U/chatbot/tool/RecommendTool.java
  src/main/java/com/ixi_U/chatbot/tool/ToolContextKey.java
  src/main/resources/prompts/embedding-prompt.txt
  src/main/resources/prompts/recommending-prompt.txt
  src/test/java/com/ixi_U/chatbot/tool/RecommendToolTest.java
Labels: feat

#53 [feat]:[SCRUM-47] access 토큰 만료 시 재발급 기능 구현
  src/main/java/com/ixi_U/common/config/SecurityConfig.java
  src/main/java/com/ixi_U/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ixi_U/user/entity/UserRole.java
  src/test/java/com/ixi_U/auth/controller/AuthControllerTest.java
  src/test/java/com/ixi_U/jwt/JwtAuthenticationFilterTest.java
  src/test/java/com/ixi_U/user/controller/ReviewControllerTest.java
  src/test/java/com/ixi_U/user/controller/UserControllerTest.java
Labels: feat

#61 [fix]:[SCRUM-114] 금칙어 시스템 임베딩 수정
  src/main/java/com/ixi_U/forbiddenWord/filters/EmbeddingSimilarityFilter.java
Labels: fix

#63 [feat]:[SCRUM-110] 챗봇 응답 거부 기능 추가
  build.gradle
  src/main/java/com/ixi_U/chatbot/config/VectorStoreConfig.java
  src/main/java/com/ixi_U/chatbot/tool/RecommendTool.java
  src/main/java/com/ixi_U/chatbot/tool/dto/MostDataAmountPlanToolDto.java
  src/main/java/com/ixi_U/chatbot/tool/dto/MostReviewPointPlanToolDto.java
  src/main/java/com/ixi_U/chatbot/tool/dto/MostReviewedPlanToolDto.java
  src/main/java/com/ixi_U/plan/repository/PlanRepository.java
  src/main/resources/prompts/filter-expression-prompt.txt
  src/main/resources/prompts/recommending-prompt.txt
  src/test/java/com/ixi_U/IxiUApplicationTests.java
  src/test/java/com/ixi_U/chatbot/tool/RecommendToolTest.java
  src/test/java/com/ixi_U/util/constants/TestConstants.java
Labels: feat

#60 [feat]:[SCRUM-109] 리뷰 신고 및 조회
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/ixi_U/user/controller/ReportController.java
  src/main/java/com/ixi_U/user/dto/request/CreateReportRequest.java
  src/main/java/com/ixi_U/user/entity/Reported.java
  src/main/java/com/ixi_U/user/exception/ReviewedException.java
  src/main/java/com/ixi_U/user/repository/ReportedRepository.java
  src/main/java/com/ixi_U/user/repository/UserRepository.java
  src/main/java/com/ixi_U/user/service/ReportService.java
  src/test/java/com/ixi_U/user/controller/ReportControllerTest.java
Labels: feat

#65 [fix]:[SCRUM-105] 신규 회원가입 에러 수정
  src/main/java/com/ixi_U/jwt/JwtAuthenticationFilter.java
Labels: fix

#66 [test]:[SCRUM-113] 요금제 개수 조회 테스트 작성
  src/docs/asciidoc/api-doc.adoc
  src/test/java/com/ixi_U/plan/controller/PlanControllerTest.java
Labels: test

#68 [fix]:[SCRUM-119] 요금제 목록 조회 캐싱, 인덱스 수정
  src/main/java/com/ixi_U/plan/entity/PlanIndexInitializer.java
  src/main/java/com/ixi_U/plan/service/PlanService.java
Labels: fix

#71 [fix]:[SCRUM-121] 요금제 데이터 타입 변경
  src/main/java/com/ixi_U/chatbot/dto/GeneratePlanDescriptionRequest.java
  src/main/java/com/ixi_U/plan/dto/request/SavePlanRequest.java
  src/main/java/com/ixi_U/plan/dto/response/PlanDetailResponse.java
  src/main/java/com/ixi_U/plan/entity/Plan.java
  src/main/java/com/ixi_U/user/dto/response/ShowCurrentSubscribedResponse.java
  src/test/java/com/ixi_U/plan/controller/PlanControllerTest.java
  src/test/java/com/ixi_U/plan/repository/PlanRepositoryTest.java
  src/test/java/com/ixi_U/user/controller/UserControllerTest.java
  src/test/java/com/ixi_U/user/repository/ReviewedRepositoryTest.java
  src/test/java/com/ixi_U/user/repository/SubscribedRepositoryTest.java
  src/test/java/com/ixi_U/user/repository/UserAndPlanRepositoryTest.java
  src/test/java/com/ixi_U/user/repository/UserRepositoryTest.java
  src/test/java/com/ixi_U/user/service/ReviewServiceTest.java
  src/test/java/com/ixi_U/user/service/SubscribedServiceTest.java
  src/test/java/com/ixi_U/user/service/UserServiceTest.java
  src/test/java/com/ixi_U/util/constants/TestConstants.java
Labels: fix

#72 [refactor]:[SCRUM-123] 필요없는 금칙어 부분 삭제 및 리뷰 필터링 적용
  src/main/java/com/ixi_U/chatbot/config/ChatBotConfig.java
  src/main/java/com/ixi_U/chatbot/config/VectorStoreConfig.java
  src/main/java/com/ixi_U/chatbot/service/ChatBotForBiddenWordDecisionService.java
  src/main/java/com/ixi_U/forbiddenWord/ChatbotFilter.java
  src/main/java/com/ixi_U/forbiddenWord/ForbiddenWordController.java
  src/main/java/com/ixi_U/forbiddenWord/ForbiddenWordLoader.java
  src/main/java/com/ixi_U/forbiddenWord/KoreanAnalyzeService.java
  src/main/java/com/ixi_U/forbiddenWord/ReviewFilter.java
  src/main/java/com/ixi_U/forbiddenWord/filters/AhoCorasickFilter.java
  src/main/java/com/ixi_U/forbiddenWord/filters/EmbeddingSimilarityFilter.java
  src/main/java/com/ixi_U/forbiddenWord/filters/LevenshteinThresholdFilter.java
  src/main/java/com/ixi_U/forbiddenWord/filters/LlmFilter.java
  src/main/java/com/ixi_U/user/exception/ReviewedException.java
  src/main/java/com/ixi_U/user/service/ReviewService.java
  src/test/java/com/ixi_U/IxiUApplicationTests.java
  src/test/java/com/ixi_U/user/service/ReviewServiceTest.java
Labels: feat, refactor

#77 [refactor]:[SCRUM-130] yml 롤백
  src/main/resources/application.yml
Labels: fix, refactor

#78 [fix]:[SCRUM-132] 요금제 비활성화/활성화 적용 로직 수정
  src/main/java/com/ixi_U/plan/dto/response/PlanDetailResponse.java
  src/main/java/com/ixi_U/plan/service/PlanService.java
  src/test/java/com/ixi_U/plan/controller/PlanControllerTest.java
Labels: fix

#79 [feat]:[SCRUM-138] 챗봇 어투 변경 거부 기능 추가
  src/main/java/com/ixi_U/chatbot/config/ChatBotConfig.java
  src/main/java/com/ixi_U/chatbot/service/ChatBotService.java
  src/main/java/com/ixi_U/chatbot/tool/RecommendTool.java
  src/main/resources/prompts/recommending-prompt.txt
Labels: feat

#80 [feat]:[SCRUM-139] 비 로그인 사용자 한정 멀티턴 기능 제거
  src/main/java/com/ixi_U/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/ixi_U/auth/repository/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/ixi_U/chatbot/config/ChatBotConfig.java
  src/main/java/com/ixi_U/chatbot/service/ChatBotService.java
  src/main/java/com/ixi_U/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ixi_U/plan/dto/response/PlanDetailResponse.java
  src/main/java/com/ixi_U/plan/service/PlanService.java
  src/main/java/com/ixi_U/user/entity/UserRole.java
  src/test/java/com/ixi_U/common/config/SecurityConfigTest.java
  src/test/java/com/ixi_U/plan/controller/PlanControllerTest.java
Labels: feat

#81 [docs]:[SCRUM-133] 깃허브 리드미 작성
  README.md
Labels: docs

#82 [docs]:[SCRUM-140] 깃허브 리드미 주요 성과 형식 통일
  README.md
Labels: docs
